version: 0.2
parameter-store:
  build_ssh_key: "emobility_build_ssh_key"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - mkdir -p ~/.ssh
      - echo "$build_ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - if [ -e .gitmodules ]; then sed -e 's/https:\/\/github.com\//git@github.com:/g' -i .gitmodules; fi
      - git submodule sync
      - git submodule update --init --recursive
      - npm install
  build:
    commands:
      - npm run build:prod
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - appspec.yml
    - 'src/aws/*.sh'
    - 'dist/**/*'
    - 'node_modules/**/*'
