version: 0.2
parameter-store:
  build_ssh_key: "emobility_build_ssh_key"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - mkdir -p ~/.ssh
      - echo "$build_ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - cat ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - echo $CODEBUILD_SOURCE_REPO_URL
      - git remote add origin git@github.com:jerome-benoit/ev-server.git
      - git fetch
      - git checkout -t origin/master-qa
      - git submodule update --init --recursive
      - npm install
  build:
    commands:
      - npm run build:prod
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - appspec.yml
    - 'src/aws/*.sh'
    - 'dist/**/*'
    - 'node_modules/**/*'
